version: '3'

services:
  tugeekdeconfianza-database:
    image: ${DB_IMAGE}:${DB_VERSION}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${LOCAL_HOST}:${DB_HOST_PORT}:3306"
    volumes:
      - ${DB_DATA}:/var/lib/mysql
      - ${DB_CONFIG}:/etc/mysql

  tugeekdeconfianza-service:
    build: ./docker
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "${tugeekdeconfianza-database}", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
    image: ghost-alpine:${GHOST_VERSION}
    restart: unless-stopped
    depends_on:
      - tugeekdeconfianza-database
    environment:
      url: ${GHOST_URL} # PRODUCTION
      # url: http://${LOCAL_HOST}:${NGINX_PORT}/ # DEVELOPMENT
      database__client: ${DB_CONNECTION}
      database__connection__host: tugeekdeconfianza-database
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      mail__transport: ${GHOST_SMTP_TRANSPORT}
      mail__options__service: ${GHOST_SMTP_SERVICE}
      mail__options__auth__user: ${GHOST_SMTP_USER}
      mail__options__auth__pass: ${GHOST_SMTP_PASSWORD}
      logging__level: ${GHOST_LOGGING_LEVEL}
      logging__rotation__period : ${GHOST_LOGGING_ROTATION_PERIOD}
    ports:
      - "${LOCAL_HOST}:${GHOST_PORT}:2368"
    volumes:
      - ${GHOST_DATA}:/var/lib/ghost/content

  tugeekdeconfianza-nginx:
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    depends_on:
      - tugeekdeconfianza-service
    environment:
      VIRTUAL_HOST: ${SERVER_NAME} # nginx-proxy container requirement
      LETSENCRYPT_HOST: ${SERVER_NAME} # letsencrypt container requirement
    ports:
      - "${LOCAL_HOST}:${NGINX_PORT}:80"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
    volumes_from:
      - tugeekdeconfianza-service

networks:
  default:
    external:
      name: nginx-proxy